export { default as Login } from './Login'
export { default as AddProperty } from './AddProperty'
export { default as Dashboard } from './Dashboard'
export { default as VerfiyEmail } from './VerifyEmail'
export { default as PropertyVerificationRequests } from './PropertyVerificationRequests'
export { default as AboutUs } from './AboutUs'
export { default as SearchProperties} from './SearchProperties'